samples:
  CGAF:
    coverages:
    - '30'
    - '30'
    - '30'
    - '30'
    descriptions:
    - Forward read files from illumina seq for Clarias gariepinus female with a 30X
      coverage
    - Reverse read files from illumina seq for Clarias gariepinus female with a 30X
      coverage
    - Forward read files from illumina seq for Clarias gariepinus female with a 30X
      coverage
    - Reverse read files from illumina seq for Clarias gariepinus female with a 30X
      coverage
    files:
    - CGAF_FDSW220159412-1r_HYH2VDSX2_L3_1.fq.gz
    - CGAF_FDSW220159412-1r_HYH2VDSX2_L3_2.fq.gz
    - CGAF_FDSW220159412-1r_HYNCNDSX2_L4_1.fq.gz
    - CGAF_FDSW220159412-1r_HYNCNDSX2_L4_2.fq.gz
    methods:
    - Illumina_PE
    - Illumina_PE
    - Illumina_PE
    - Illumina_PE
    orientations:
    - R1
    - R2
    - R1
    - R2
    outputs: {}
    paths:
    - ~/catfish_illumina/CGAF/
    - ~/catfish_illumina/CGAF/
    - ~/catfish_illumina/CGAF/
    - ~/catfish_illumina/CGAF/
    prefixes:
    - L3
    - L3
    - L4
    - L4
    sex: female
    species: Clarias_gariepinus
  CGAM:
    coverages:
    - '90'
    - '90'
    - NA
    - '25'
    - '40'
    descriptions:
    - 'Forward read files from illumina seq for Clarias gariepinus male with a coverage
      of 90X '
    - 'Reverse read files from illumina seq for Clarias gariepinus male with a coverage
      of 90X '
    - 'HiC reads for Clarias gariepinus male '
    - nanopore reads for Clarias gariepinus male with a coverage of 25X
    - pacbio reads for Clarias gariepinus male with a coverage of 40X
    files:
    - CGAM_FDSW220157897-1r_HYJYHDSX2_L2_1.fq.gz
    - CGAM_FDSW220157897-1r_HYJYHDSX2_L2_2.fq.gz
    - R1
    - R1
    - R1
    methods:
    - Illumina_PE
    - Illumina_PE
    - HiC
    - Nanopore
    - PacBio
    orientations:
    - R1
    - R2
    - ''
    - ''
    - ''
    outputs: {}
    paths:
    - ~/catfish_illumina/CGAM/
    - ~/catfish_illumina/CGAM/
    - ''
    - ''
    - ''
    prefixes:
    - L2
    - L2
    - ''
    - ''
    - ''
    sex: male
    species: Clarias_gariepinus
  CHAF:
    coverages:
    - '30'
    - '30'
    descriptions:
    - Forward read files from illumina seq for Clarias hybrid female with a coverage
      of 30X
    - Reverse read files from illumina seq for Claris hybrid female with a coverage
      of 30X
    files:
    - R1
    - R2
    methods:
    - Illumina_PE
    - Illumina_PE
    orientations:
    - R1
    - R2
    outputs: {}
    paths:
    - ''
    - ''
    prefixes:
    - ''
    - ''
    sex: female
    species: Clarias_hybrid
  CHAM:
    coverages:
    - '30'
    - '30'
    descriptions:
    - Forward read files from illumina seq for Clarias hybrid male with a coverage
      of 30X
    - Reverse read files from illumina seq for Clarias hybrid male with a coverage
      of 30X
    files:
    - R1
    - R2
    methods:
    - Illumina_PE
    - Illumina_PE
    orientations:
    - R1
    - R2
    outputs: {}
    paths:
    - ''
    - ''
    prefixes:
    - ''
    - ''
    sex: male
    species: Clarias_hybrid
  CMAF:
    coverages:
    - '30'
    - '30'
    - '30'
    - '30'
    descriptions:
    - Forward read files from illumina seq for Clarias macrocephalus femaile with
      a coverage of 30X
    - Reverse read files from illumina seq for  Clarias macrocephalus femaile with
      a coverage of 30X
    - Forward read files from illumina seq for Clarias macrocephalus femaile with
      a coverage of 30X
    - Reverse read files from illumina seq for  Clarias macrocephalus femaile with
      a coverage of 30X
    files:
    - CMAF_FDSW220157896-1r_HJCYWDSX3_L1_1.fq.gz
    - CMAF_FDSW220157896-1r_HJCYWDSX3_L1_2.fq.gz
    - CMAF_FDSW220157896-1r_HYJY5DSX2_L3_1.fq.gz
    - CMAF_FDSW220157896-1r_HYJY5DSX2_L3_2.fq.gz
    methods:
    - Illumina_PE
    - Illumina_PE
    - Illumina_PE
    - Illumina_PE
    orientations:
    - R1
    - R2
    - R1
    - R2
    outputs: {}
    paths:
    - ~/catfish_illumina/CMAF/
    - ~/catfish_illumina/CMAF/
    - ~/catfish_illumina/CMAF/
    - ~/catfish_illumina/CMAF/
    prefixes:
    - L1
    - L1
    - L2
    - L2
    sex: female
    species: Clarias_macrocephalus
  CMAM:
    coverages:
    - '90'
    - '90'
    - NA
    - '25'
    - '40'
    descriptions:
    - Forward read files from illumina seq for Clarias macrocephalus male with a 90X
      coverage
    - Reverse read files from illumina seq for Clarias macrocephalus male with a 90X
      coverage
    - 'HiC reads for Clarias macrocephalus male '
    - nanopore reads for Clarias macrocephalus male with a coverage of 25X
    - pacbio reads for Clarias macrocephalus male with a coverage of 40X
    files:
    - CMAM1_FDSW220159411-1r_HYH2VDSX2_L3_1.fq.gz
    - CMAM1_FDSW220159411-1r_HYH2VDSX2_L3_2.fq.gz
    - R1
    - R1
    - R1
    methods:
    - Illumina_PE
    - Illumina_PE
    - HiC
    - Nanopore
    - PacBio
    orientations:
    - R1
    - R2
    - ''
    - ''
    - ''
    outputs: {}
    paths:
    - ~/catfish_illumina/CMAM1/
    - ~/catfish_illumina/CMAM1/
    - ''
    - ''
    - ''
    prefixes:
    - L3
    - L3
    - ''
    - ''
    - ''
    sex: male
    species: Clarias_macrocephalus
